export const  card = [
    {
    image: "https://picsum.photos/seed/picsum/200",
    name: "HOTEL ORBI CITY DOWNTOWN FOR BATUMI",
    rating:"very good",
    ratingNumber:"8.4",
    review:"332",
    location:"new boulevard, batumi",
    distance:"2.3",
    specification:"beachfront",
    description:"Set in Batumi, HOTEL ORBI CITY DOWNTOWN FOR BATUMI offers beachfront accommodation 800 metres from Batumi Beach and provides various facilities, such as an open-air bath and a casino.",
    },
    {
        image: "./images/524208151.webp",
        name: "aparthotel batumi in orbi city seaview",
        rating:"superb",
        ratingNumber:"9.3",
        review:"209",
        location:"new boulevard, batumi",
        distance:"2.5",
        specification:"200 m from beach",
        description:"Set 500 metres from Batumi Beach, Aparthotel Batumi In Orbi City Seaview offers 5-star accommodation in Batumi and has a garden, a restaurant and a bar.",
    },
    {
        image: "./images/524208151.webp",
        name: "orbi city batumi star",
        rating:"superb",
        ratingNumber:"9.1",
        review:"16",
        location:"new boulevard, batumi",
        distance:"2.3",
        specification:"beachfront",
        description:"A recently renovated aparthotel in Batumi and within 600 metres of Batumi Beach, Apartment from batumi features a private beach area, comfortable allergy-free rooms and free WiFi.",
    },
    {
        image: "./images/524208151.webp",
        name: "orbi city batumi star",
        rating:"superb",
        ratingNumber:"9.1",
        review:"16",
        location:"new boulevard, batumi",
        distance:"2.3",
        specification:"beachfront",
        description:"A recently renovated aparthotel in Batumi and within 600 metres of Batumi Beach, Apartment from batumi features a private beach area, comfortable allergy-free rooms and free WiFi.",
    },
    {
        image: "./images/524208151.webp",
        name: "orbi city batumi star",
        rating:"superb",
        ratingNumber:"9.1",
        review:"16",
        location:"new boulevard, batumi",
        distance:"2.3",
        specification:"beachfront",
        description:"A recently renovated aparthotel in Batumi and within 600 metres of Batumi Beach, Apartment from batumi features a private beach area, comfortable allergy-free rooms and free WiFi.",
    },
    {
        image: "./images/524208151.webp",
        name: "orbi city batumi star",
        rating:"superb",
        ratingNumber:"9.1",
        review:"16",
        location:"new boulevard, batumi",
        distance:"2.3",
        specification:"beachfront",
        description:"A recently renovated aparthotel in Batumi and within 600 metres of Batumi Beach, Apartment from batumi features a private beach area, comfortable allergy-free rooms and free WiFi.",
    },
    {
        image: "./images/524208151.webp",
        name: "orbi city batumi star",
        rating:"superb",
        ratingNumber:"9.1",
        review:"16",
        location:"new boulevard, batumi",
        distance:"2.3",
        specification:"beachfront",
        description:"A recently renovated aparthotel in Batumi and within 600 metres of Batumi Beach, Apartment from batumi features a private beach area, comfortable allergy-free rooms and free WiFi.",
    },
    {
        image: "./images/524208151.webp",
        name: "orbi city batumi star",
        rating:"superb",
        ratingNumber:"9.1",
        review:"16",
        location:"new boulevard, batumi",
        distance:"2.3",
        specification:"beachfront",
        description:"A recently renovated aparthotel in Batumi and within 600 metres of Batumi Beach, Apartment from batumi features a private beach area, comfortable allergy-free rooms and free WiFi.",
    },
    {
        image: "./images/524208151.webp",
        name: "orbi city batumi star",
        rating:"superb",
        ratingNumber:"9.1",
        review:"16",
        location:"new boulevard, batumi",
        distance:"2.3",
        specification:"beachfront",
        description:"A recently renovated aparthotel in Batumi and within 600 metres of Batumi Beach, Apartment from batumi features a private beach area, comfortable allergy-free rooms and free WiFi.",
    },
    {
        image: "./images/524208151.webp",
        name: "orbi city batumi star",
        rating:"superb",
        ratingNumber:"9.1",
        review:"16",
        location:"new boulevard, batumi",
        distance:"2.3",
        specification:"beachfront",
        description:"A recently renovated aparthotel in Batumi and within 600 metres of Batumi Beach, Apartment from batumi features a private beach area, comfortable allergy-free rooms and free WiFi.",
    },
    {
        image: "./images/524208151.webp",
        name: "orbi city batumi star",
        rating:"superb",
        ratingNumber:"9.1",
        review:"16",
        location:"new boulevard, batumi",
        distance:"2.3",
        specification:"beachfront",
        description:"A recently renovated aparthotel in Batumi and within 600 metres of Batumi Beach, Apartment from batumi features a private beach area, comfortable allergy-free rooms and free WiFi.",
    },
    {
        image: "./images/524208151.webp",
        name: "orbi city batumi star",
        rating:"superb",
        ratingNumber:"9.1",
        review:"16",
        location:"new boulevard, batumi",
        distance:"2.3",
        specification:"beachfront",
        description:"A recently renovated aparthotel in Batumi and within 600 metres of Batumi Beach, Apartment from batumi features a private beach area, comfortable allergy-free rooms and free WiFi.",
    },
    {
        image: "./images/524208151.webp",
        name: "orbi city batumi star",
        rating:"superb",
        ratingNumber:"9.1",
        review:"16",
        location:"new boulevard, batumi",
        distance:"2.3",
        specification:"beachfront",
        description:"A recently renovated aparthotel in Batumi and within 600 metres of Batumi Beach, Apartment from batumi features a private beach area, comfortable allergy-free rooms and free WiFi.",
    },
    {
        image: "./images/524208151.webp",
        name: "orbi city batumi star",
        rating:"superb",
        ratingNumber:"9.1",
        review:"16",
        location:"new boulevard, batumi",
        distance:"2.3",
        specification:"beachfront",
        description:"A recently renovated aparthotel in Batumi and within 600 metres of Batumi Beach, Apartment from batumi features a private beach area, comfortable allergy-free rooms and free WiFi.",
    },
]